// Single source of truth for non-translatable, real business data.
// Translatable copy lives in messages/{tr,en}.json.

export const WHATSAPP_NUMBER = '905303844482'; // E.164 without '+'
export const PHONE_DISPLAY = '+90 530 384 44 82';
export const PHONE_HREF = 'tel:+905303844482';
export const EMAIL = 'info@ttaskiran.com';

export const ADDRESS_LINE =
  'Varlık Mh. Hızır Reis Cad. No:29/3 Muratpaşa / ANTALYA';
export const MAPS_QUERY = encodeURIComponent(
  'Varlık Mah. Hızır Reis Cad. No:29 Muratpaşa Antalya',
);
export const MAPS_URL = `https://www.google.com/maps/search/?api=1&query=${MAPS_QUERY}`;
export const MAPS_EMBED = `https://maps.google.com/maps?q=${MAPS_QUERY}&z=15&output=embed`;

export const SOCIAL = {
  instagram: {
    handle: '@ttaskiranltdsti',
    url: 'https://www.instagram.com/ttaskiranltdsti/',
  },
  facebook: {
    handle: 'TTaskiran.Ltd.Sti',
    url: 'https://www.facebook.com/TTaskiran.Ltd.Sti',
  },
} as const;

export function whatsappLink(message?: string) {
  const base = `https://wa.me/${WHATSAPP_NUMBER}`;
  return message ? `${base}?text=${encodeURIComponent(message)}` : base;
}

// The four real, business-validated categories (order is fixed).
export const CATEGORY_KEYS = ['hotel', 'villa', 'business', 'residence'] as const;
export type CategoryKey = (typeof CATEGORY_KEYS)[number];

// ── Real projects (generated by scripts/import-projects.mjs) ────────────────
import projectsData from './projects.json';

export type ProjectImage = { src: string; w: number; h: number };
export type Project = {
  slug: string;
  name: string;
  category: CategoryKey;
  cover: string;
  images: ProjectImage[];
};

export const PROJECTS = projectsData as Project[];

export function projectsByCategory(category: CategoryKey): Project[] {
  return PROJECTS.filter((p) => p.category === category);
}
export function projectBySlug(slug: string): Project | undefined {
  return PROJECTS.find((p) => p.slug === slug);
}

// Generated placeholder fallbacks (used only where no real project exists yet)
const PLACEHOLDER_IMAGES: Record<CategoryKey, string> = {
  hotel: '/images/hotel.svg',
  villa: '/images/villa.svg',
  business: '/images/business.svg',
  residence: '/images/residence.svg',
};
const PLACEHOLDER_GALLERY: Record<CategoryKey, string[]> = {
  hotel: Array.from({ length: 6 }, (_, i) => `/images/gallery/hotel-${i + 1}.svg`),
  villa: Array.from({ length: 6 }, (_, i) => `/images/gallery/villa-${i + 1}.svg`),
  business: Array.from({ length: 6 }, (_, i) => `/images/gallery/business-${i + 1}.svg`),
  residence: Array.from({ length: 6 }, (_, i) => `/images/gallery/residence-${i + 1}.svg`),
};

// Category cover = first real project's cover, else placeholder (Villa for now).
function categoryCover(category: CategoryKey): string {
  return projectsByCategory(category)[0]?.cover ?? PLACEHOLDER_IMAGES[category];
}

export const CATEGORY_IMAGES: Record<CategoryKey, string> = {
  hotel: categoryCover('hotel'),
  villa: categoryCover('villa'),
  business: categoryCover('business'),
  residence: categoryCover('residence'),
};

export function galleryImagesFor(category: CategoryKey): string[] {
  const real = projectsByCategory(category).flatMap((p) => p.images.map((im) => im.src));
  return real.length ? real : PLACEHOLDER_GALLERY[category];
}

// Before/After slider — two St. Regis suite design directions (same room).
const stRegis = projectBySlug('st-regis');
export const BEFORE_AFTER_IMAGES = stRegis
  ? {
      before: stRegis.images[Math.min(2, stRegis.images.length - 2)].src,
      after: stRegis.images[Math.min(3, stRegis.images.length - 1)].src,
    }
  : { before: '/images/letven-before.svg', after: '/images/letven-after.svg' };

export function isCategoryKey(value: string): value is CategoryKey {
  return (CATEGORY_KEYS as readonly string[]).includes(value);
}
